wandb_version: 1

objective:
  desc: null
  value: multiclass
num_class:
  desc: null
  value: 6
metric:
  desc: null
  value: multi_logloss
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1721579475
    t:
      1:
      - 5
      - 6
      - 8
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 53
      - 55
      3:
      - 7
      - 16
      - 23
      - 25
      - 63
      4: 3.12.4
      5: 0.17.5
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
    m:
    - 1: validation_multi_logloss
      6:
      - 3
      7:
      - 1
num_iterations:
  desc: null
  value: 30
